// Chatbot Constants
export const CHATBOT_CONNECT_REQUEST = 'CHATBOT_CONNECT_REQUEST';
export const CHATBOT_CONNECT_SUCCESS = 'CHATBOT_CONNECT_SUCCESS';
export const CHATBOT_CONNECT_FAIL = 'CHATBOT_CONNECT_FAIL';

export const CHATBOT_DISCONNECT = 'CHATBOT_DISCONNECT';

export const CHATBOT_AUTH_REQUEST = 'CHATBOT_AUTH_REQUEST';
export const CHATBOT_AUTH_SUCCESS = 'CHATBOT_AUTH_SUCCESS';
export const CHATBOT_AUTH_FAIL = 'CHATBOT_AUTH_FAIL';

export const CHATBOT_SEND_MESSAGE_REQUEST = 'CHATBOT_SEND_MESSAGE_REQUEST';
export const CHATBOT_SEND_MESSAGE_SUCCESS = 'CHATBOT_SEND_MESSAGE_SUCCESS';
export const CHATBOT_SEND_MESSAGE_FAIL = 'CHATBOT_SEND_MESSAGE_FAIL';

export const CHATBOT_RECEIVE_MESSAGE = 'CHATBOT_RECEIVE_MESSAGE';

export const CHATBOT_TYPING = 'CHATBOT_TYPING';
export const CHATBOT_TYPING_STOP = 'CHATBOT_TYPING_STOP';

export const CHATBOT_TOGGLE_WIDGET = 'CHATBOT_TOGGLE_WIDGET';

export const CHATBOT_CLEAR_MESSAGES = 'CHATBOT_CLEAR_MESSAGES';

export const CHATBOT_LOAD_HISTORY_REQUEST = 'CHATBOT_LOAD_HISTORY_REQUEST';
export const CHATBOT_LOAD_HISTORY_SUCCESS = 'CHATBOT_LOAD_HISTORY_SUCCESS';
export const CHATBOT_LOAD_HISTORY_FAIL = 'CHATBOT_LOAD_HISTORY_FAIL';

export const CHATBOT_NEW_CONVERSATION = 'CHATBOT_NEW_CONVERSATION';
export const CHATBOT_SET_CONVERSATION_ID = 'CHATBOT_SET_CONVERSATION_ID';

export const CHATBOT_ERROR = 'CHATBOT_ERROR';
